jobs:
  build:
    name: Build Parquet with JDK ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@master
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: before_install
      run: 'sudo apt-get update -qq

        sudo apt-get install -qq protobuf-compiler

        sudo apt-get install -qq libboost-dev libboost-test-dev libboost-program-options-dev
        libevent-dev automake libtool flex bison pkg-config g++ libssl-dev

        wget -qO- https://archive.apache.org/dist/thrift/0.19.0/thrift-0.19.0.tar.gz
        | tar zxf -

        cd thrift-0.19.0/

        chmod +x ./configure

        ./configure --disable-libs

        sudo make install

        '
    - continue-on-error: true
      name: install
      run: 'mvn install --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true
        -Djava.version=${{ matrix.java }}

        '
    - continue-on-error: true
      name: verify
      run: 'mvn verify --batch-mode javadoc:javadoc

        '
    strategy:
      fail-fast: false
      matrix:
        java:
        - '8'
        - '11'
        - '17'
name: Test
on:
  repository_dispatch:
    types: trigger-ga___test.yml
